[tool.poetry]
name = "homework-05"
version = "0.1.0"
description = ""
authors = ["redtomat87 <mr_tomat@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Flask = "^3.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
